// Mirrors the Prisma enums in apps/api/prisma/schema.prisma — keep in sync.

export enum Role {
  PROSUMER = "PROSUMER",
  CONSUMER = "CONSUMER",
  UTILITY = "UTILITY",
  REGULATOR = "REGULATOR",
  ADMIN = "ADMIN",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  DELETED = "DELETED",
}

export enum MeterType {
  SOLAR = "SOLAR",
  CONSUMER = "CONSUMER",
  BIDIRECTIONAL = "BIDIRECTIONAL",
}

export enum MeterStatus {
  ACTIVE = "ACTIVE",
  OFFLINE = "OFFLINE",
  SUSPENDED = "SUSPENDED",
  FLAGGED = "FLAGGED",
}

export enum ZoneStatus {
  NORMAL = "NORMAL",
  CONGESTED = "CONGESTED",
  OUTAGE = "OUTAGE",
}

export enum Congestion {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum CreditStatus {
  VERIFIED = "VERIFIED",
  MINTED = "MINTED",
  AVAILABLE = "AVAILABLE",
  LISTED = "LISTED",
  RESERVED = "RESERVED",
  PURCHASED = "PURCHASED",
  SETTLED = "SETTLED",
  RETIRED = "RETIRED",
  EXPIRED = "EXPIRED",
  FROZEN = "FROZEN",
}

export enum ListingStatus {
  ACTIVE = "ACTIVE",
  PARTIAL = "PARTIAL",
  RESERVED = "RESERVED",
  SOLD = "SOLD",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum MatchStatus {
  MATCHED = "MATCHED",
  RESERVED = "RESERVED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum TxStatus {
  PENDING = "PENDING",
  MATCHED = "MATCHED",
  RESERVED = "RESERVED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID = "PAID",
  CREDIT_TRANSFERRED = "CREDIT_TRANSFERRED",
  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",
  SETTLED = "SETTLED",
  COMPLETED = "COMPLETED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  BLOCKCHAIN_PENDING = "BLOCKCHAIN_PENDING",
  BLOCKCHAIN_FAILED = "BLOCKCHAIN_FAILED",
  SETTLEMENT_FAILED = "SETTLEMENT_FAILED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum PayStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum SettleStatus {
  PENDING = "PENDING",
  SUBMITTED = "SUBMITTED",
  SETTLED = "SETTLED",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  MISMATCH = "MISMATCH",
}

export enum ReadingStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  FLAGGED = "FLAGGED",
  REJECTED = "REJECTED",
}

export const ERROR_CODES = [
  "VALIDATION_ERROR",
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "READING_NOT_VERIFIED",
  "CREDITS_ALREADY_ISSUED",
  "INSUFFICIENT_CREDITS",
  "CREDIT_EXPIRED",
  "PRICE_OUT_OF_BAND",
  "SELF_TRADE",
  "GRID_CONGESTED",
  "ZONE_OUTAGE",
  "ZONE_NOT_ELIGIBLE",
  "PAYMENT_FAILED",
  "SETTLEMENT_FAILED",
  "DUPLICATE_REQUEST",
  "METER_NOT_ACTIVE",
  "RATE_LIMITED",
  "TRANSACTION_TIMEOUT",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
